### PR TITLE
maybe a bit faster

### PR DESCRIPTION
**Pull request by peterferrie**

### CODE REVIEW

**Comment by davidgiven** [comment]
Thanks!

I'm actually travelling, so I won't be able to test this until I get back (I want to benchmark any changes on a known system). That'll be in a couple of weeks --- I'll get back to you then.

Feel free to remind me if you think I've forgotten about you.

**Comment by peterferrie** [comment]
Hi,

> Feel free to remind me if you think I've forgotten about you.

Did this work after all?

**Comment by davidgiven** [comment]
Oh, wow, I completely forgot about this! Sorry.

I've built it and done a benchmark and it turns out to be slightly _slower_ than trunk; 2710px/s vs 2732px/s for the default render (via b-em), but I'm not entirely sure why. The optimisations all look valid.

Can you check that you're up to date with master? Maybe there's an additional optimisation your code hasn't picked up (sorry, not good enough with git to do that myself).

**Comment by davidgiven** [comment]
Oh, d'oh, I don't need git for that, I can just diff the files. Yes, there's some changes you haven't picked up --- it's the change which turns off interrupts during rendering, which saves a little. Could you update?

**Comment by peterferrie** [comment]
> Oh, d'oh, I don't need git for that, I can just diff the files. Yes, there's
> some changes you haven't picked up --- it's the change which turns off
> interrupts during rendering, which saves a little. Could you update?

Okay, I'll update my code and then resubmit the PR.
Thanks.

**Comment by peterferrie** [comment]
Oh, the benchmark is including the time to run the shutdown routine,
which is slower than the original.  The important code is faster.

**Comment by davidgiven** [comment]
No problem --- no rush.

**Comment by peterferrie** [comment]
Please try it now.

**Comment by davidgiven** [comment]
Okay, so I tried to apply your changes and it was a complete mess --- utterly unrelated from the current version. This turns out to be because hg has failed to push the master branch correctly for almost exactly 
a year. Argh. During that time the performance has improved from 2712 to 2732 px/s. (Admittedly that's only one day's work as I've done almost nothing on this for that last year.)

I'm sorry for wasting your time. The good news is that I've manually applied your changes to the current master (and actually pushed it this time), because I like the kernel swap idea, but the microoptimisations they don't make a measurable difference to the performance as they're in a relatively low-priority area. I've added the ones which I think make the code clearer.

Thanks very much!

**Pull request closed without merging**
