### PR TITLE
a bit faster

### PR DESCRIPTION
**Pull request by peterferrie**

### CODE REVIEW

**Comment by davidgiven** [comment]
Thanks very much --- but you are aware that this is the now-obsolete version of the program, right? The one in the default branch, using reenigne's calculation algorithm, takes a quarter of the time and works at 14 bit precision rather than 8.

**Comment by peterferrie** [comment]
> Thanks very much --- but you are aware that this is the now-obsolete version
> of the program, right? The one in the default branch, using reenigne's
> calculation algorithm, takes a quarter of the time and works at 14 bit
> precision rather than 8.

Ha, that's funny.  It was the version that was shared today among
Apple enthusiasts on a newsgroup.  I will check the other now.

**Comment by davidgiven** [comment]
Hmm, the new version got shared on the 6502 G+ group the other day, but I've checked and the link is correct...

Anyway, the new version is at http://cowlark.com/2018-05-26-bogomandel/.

**Comment by peterferrie** [comment]
> Hmm, the new version got shared on the 6502 G+ group the other day, but I've
> checked and the link is correct...

Yes, probably an unrelated news item that got picked up late.

> Anyway, the new version is at http://cowlark.com/2018-05-26-bogomandel/.

Okay, I have a tiny PR for that one, assuming that my changes work correctly.

**Pull request merged**
